### ISSUE TITLE
resources memory hugepages 显示内容不对

### ISSUE THREAD

**Issue by Lt0** [Lt0/sysmon#9]

**Comment by Lt0** [comment]
你圈出来的这个位置是 swap 显示的内容, 目前没有配置交换分区的情况下会这么显示

**Comment by Lt0** [comment]
#13 另外开了一个 issue 来跟踪这个问题, 这个 issue 是 hugepages 显示问题的, 已经 fix 了没有更新这里的状态.

**Comment by zhuSilence** [comment]
好的。
